backend:
  name: github
  repo: LindaOjo/Lindaojo.com # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "blog"
    folder: "content/blog/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: 'Image', name: 'image', widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", dateformat: "YYYY-MM-DD", format: "YYYY-MM-DD"}
      - {label: "Duration", name: "duration", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"} 
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "isBlogPost", name: "isBlogPost", widget: "boolean", required: true}
  - name: "poem"
    label: "poem"
    folder: "content/blog/poems"

    create: true
    slug: "{{slug}}"
    fields:
      - {label: 'Image', name: 'image', widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "datetime", widget: "datetime", date_format: "YYYY.MM.DD"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "isBlogPost", name: "isBlogPost", widget: "boolean", default: "false"}
      